// UPLOAD DATA
export const API_BL_UPLOAD_CSV_REQUEST = 'API_BL_UPLOAD_CSV_REQUEST'
export const API_BL_UPLOAD_CSV_SUCCESS = 'API_BL_UPLOAD_CSV_SUCCESS'
export const API_BL_UPLOAD_CSV_FAIL = 'API_BL_UPLOAD_CSV_FAIL'
export const API_BL_UPLOAD_CSV_RESET = 'API_BL_UPLOAD_CSV_RESET'


//SHOW LIST DATA UPLOAD
export const PHONE_API_BL_LIST_REQUEST = 'PHONE_API_BL_LIST_REQUEST'
export const PHONE_API_BL_LIST_SUCCESS = 'PHONE_API_BL_LIST_SUCCESS'
export const PHONE_API_BL_LIST_FAIL = 'PHONE_API_BL_LIST_FAIL'
export const PHONE_API_BL_LIST_RESET = 'PHONE_API_BL_LIST_RESET'


//SHOW LIST DATA UPLOAD
export const API_BL_LIST_REQUEST = 'API_BL_LIST_REQUEST'
export const API_BL_LIST_SUCCESS = 'API_BL_LIST_SUCCESS'
export const API_BL_LIST_FAIL = 'API_BL_LIST_FAIL'
export const API_BL_LIST_RESET = 'API_BL_LIST_RESET'

//CLEAN DATA LOOK UP
export const PHONE_LOOP_UP_REQUEST = 'PHONE_LOOP_UP_REQUEST'
export const PHONE_LOOP_UP_SUCCESS = 'PHONE_LOOP_UP_SUCCESS'
export const PHONE_LOOP_UP_FAIL = 'PHONE_LOOP_UP_FAIL'
export const PHONE_LOOP_UP_RESET = 'PHONE_LOOP_UP_RESET'

// IMPORT CLEAN DATA
export const IMPORT_CLEAN_DATA_REQUEST = 'IMPORT_CLEAN_DATA_REQUEST'
export const IMPORT_CLEAN_DATA_SUCCESS = 'IMPORT_CLEAN_DATA_SUCCESS'
export const IMPORT_CLEAN_DATA_FAIL = 'IMPORT_CLEAN_DATA_FAIL'
export const IMPORT_CLEAN_DATA_RESET = 'IMPORT_CLEAN_DATA_RESET'