export const BLACK_LIST_PHONE_LIST_REQUEST = 'BLACK_LIST_PHONE_LIST_REQUEST'
export const BLACK_LIST_PHONE_LIST_SUCCESS = 'BLACK_LIST_PHONE_LIST_SUCCESS'
export const BLACK_LIST_PHONE_LIST_FAIL = 'BLACK_LIST_PHONE_LIST_FAIL'
export const BLACK_LIST_PHONE_LIST_RESET = 'BLACK_LIST_PHONE_LIST_RESET'

export const BLACK_LIST_PHONE_REGISTER_REQUEST = 'BLACK_LIST_PHONE_REGISTER_REQUEST'
export const BLACK_LIST_PHONE_REGISTER_SUCCESS = 'BLACK_LIST_PHONE_REGISTER_SUCCESS'
export const BLACK_LIST_PHONE_REGISTER_FAIL = 'BLACK_LIST_PHONE_REGISTER_FAIL'
export const BLACK_LIST_PHONE_REGISTER_RESET = 'BLACK_LIST_PHONE_REGISTER_RESET'

export const BLACK_LIST_PHONE_DELETE_REQUEST = 'BLACK_LIST_PHONE_DELETE_REQUEST'
export const BLACK_LIST_PHONE_DELETE_SUCCESS = 'BLACK_LIST_PHONE_DELETE_SUCCESS'
export const BLACK_LIST_PHONE_DELETE_FAIL = 'BLACK_LIST_PHONE_DELETE_FAIL'
export const BLACK_LIST_PHONE_DELETE_RESET = 'BLACK_LIST_PHONE_DELETE_RESET'

export const BLACK_LIST_PHONE_UPDATE_REQUEST = 'BLACK_LIST_PHONE_UPDATE_REQUEST'
export const BLACK_LIST_PHONE_UPDATE_SUCCESS = 'BLACK_LIST_PHONE_UPDATE_SUCCESS'
export const BLACK_LIST_PHONE_UPDATE_FAIL = 'BLACK_LIST_PHONE_UPDATE_FAIL'
export const BLACK_LIST_PHONE_UPDATE_RESET = 'BLACK_LIST_PHONE_UPDATE_RESET'