export const BAD_AREA_LIST_REQUEST = 'BAD_AREA_LIST_REQUEST'
export const BAD_AREA_LIST_SUCCESS = 'BAD_AREA_LIST_SUCCESS'
export const BAD_AREA_LIST_FAIL = 'BAD_AREA_LIST_FAIL'
export const BAD_AREA_LIST_RESET = 'BAD_AREA_LIST_RESET'

export const BAD_AREA_REGISTER_REQUEST = 'BAD_AREA_REGISTER_REQUEST'
export const BAD_AREA_REGISTER_SUCCESS = 'BAD_AREA_REGISTER_SUCCESS'
export const BAD_AREA_REGISTER_FAIL = 'BAD_AREA_REGISTER_FAIL'
export const BAD_AREA_REGISTER_RESET = 'BAD_AREA_REGISTER_RESET'

export const BAD_AREA_DELETE_REQUEST = 'BAD_AREA_DELETE_REQUEST'
export const BAD_AREA_DELETE_SUCCESS = 'BAD_AREA_DELETE_SUCCESS'
export const BAD_AREA_DELETE_FAIL = 'BAD_AREA_DELETE_FAIL'
export const BAD_AREA_DELETE_RESET = 'BAD_AREA_DELETE_RESET'

export const BAD_AREA_UPDATE_REQUEST = 'BAD_AREA_UPDATE_REQUEST'
export const BAD_AREA_UPDATE_SUCCESS = 'BAD_AREA_UPDATE_SUCCESS'
export const BAD_AREA_UPDATE_FAIL = 'BAD_AREA_UPDATE_FAIL'
export const BAD_AREA_UPDATE_RESET = 'BAD_AREA_UPDATE_RESET'