export const EXPORT_LIST_REQUEST = 'EXPORT_LIST_REQUEST'
export const EXPORT_LIST_SUCCESS = 'EXPORT_LIST_SUCCESS'
export const EXPORT_LIST_FAIL = 'EXPORT_LIST_FAIL'
export const EXPORT_LIST_RESET = 'EXPORT_LIST_RESET'

export const MASTER_CCC_REQUEST = 'MASTER_CCC_REQUEST'
export const MASTER_CCC_SUCCESS = 'MASTER_CCC_SUCCESS'
export const MASTER_CCC_FAIL = 'MASTER_CCC_FAIL'
export const MASTER_CCC_RESET = 'MASTER_CCC_RESET'