export const CLICKER_REQUEST = 'CLICKER_REQUEST'
export const CLICKER_SUCCESS = 'CLICKER_SUCCESS'
export const CLICKER_FAIL = 'CLICKER_FAIL'
export const CLICKER_RESET = 'CLICKER_RESET'

export const CONVERTER_REQUEST = 'CONVERTER_REQUEST'
export const CONVERTER_SUCCESS = 'CONVERTER_SUCCESS'
export const CONVERTER_FAIL = 'CONVERTER_FAIL'
export const CONVERTER_RESET = 'CONVERTER_RESET'

export const CCC_REQUEST = 'CCC_REQUEST'
export const CCC_SUCCESS = 'CCC_SUCCESS'
export const CCC_FAIL = 'CCC_FAIL'
export const CCC_RESET = 'CCC_RESET'

export const BAD_STATE_REQUEST = 'BAD_STATE_REQUEST'
export const BAD_STATE_SUCCESS = 'BAD_STATE_SUCCESS'
export const BAD_STATE_FAIL = 'BAD_STATE_FAIL'
export const BAD_STATE_RESET = 'BAD_STATE_RESET'

export const HARD_BOUNCE_REQUEST = 'HARD_BOUNCE_REQUEST'
export const HARD_BOUNCE_SUCCESS = 'HARD_BOUNCE_SUCCESS'
export const HARD_BOUNCE_FAIL = 'HARD_BOUNCE_FAIL'
export const HARD_BOUNCE_RESET = 'HARD_BOUNCE_RESET'

export const SUPPRESSED_REQUEST = 'SUPPRESSED_REQUEST'
export const SUPPRESSED_SUCCESS = 'SUPPRESSED_SUCCESS'
export const SUPPRESSED_FAIL = 'SUPPRESSED_FAIL'
export const SUPPRESSED_RESET = 'SUPPRESSED_RESET'

export const VERIZON_REQUEST = 'VERIZON_REQUEST'
export const VERIZON_SUCCESS = 'VERIZON_SUCCESS'
export const VERIZON_FAIL = 'VERIZON_FAIL'
export const VERIZON_RESET = 'VERIZON_RESET'

export const ATT_REQUEST = 'ATT_REQUEST'
export const ATT_SUCCESS = 'ATT_SUCCESS'
export const ATT_FAIL = 'ATT_FAIL'
export const ATT_RESET = 'ATT_RESET'

export const SPRINT_REQUEST = 'SPRINT_REQUEST'
export const SPRINT_SUCCESS = 'SPRINT_SUCCESS'
export const SPRINT_FAIL = 'SPRINT_FAIL'
export const SPRINT_RESET = 'SPRINT_RESET'

export const T_MOBILE_REQUEST = 'T_MOBILE_REQUEST'
export const T_MOBILE_SUCCESS = 'T_MOBILE_SUCCESS'
export const T_MOBILE_FAIL = 'T_MOBILE_FAIL'
export const T_MOBILE_RESET = 'T_MOBILE_RESET'

export const US_CELLULAR_REQUEST = 'US_CELLULAR_REQUEST'
export const US_CELLULAR_SUCCESS = 'US_CELLULAR_SUCCESS'
export const US_CELLULAR_FAIL = 'US_CELLULAR_FAIL'
export const US_CELLULAR_RESET = 'US_CELLULAR_RESET'
