export const PHONE_CLEAN_LIST_REQUEST = 'PHONE_CLEAN_LIST_REQUEST'
export const PHONE_CLEAN_LIST_SUCCESS = 'PHONE_CLEAN_LIST_SUCCESS'
export const PHONE_CLEAN_LIST_FAIL = 'PHONE_CLEAN_LIST_FAIL'
export const PHONE_CLEAN_LIST_RESET = 'PHONE_CLEAN_LIST_RESET'

export const PHONE_CLEAN_REGISTER_REQUEST = 'PHONE_CLEAN_REGISTER_REQUEST'
export const PHONE_CLEAN_REGISTER_SUCCESS = 'PHONE_CLEAN_REGISTER_SUCCESS'
export const PHONE_CLEAN_REGISTER_FAIL = 'PHONE_CLEAN_REGISTER_FAIL'
export const PHONE_CLEAN_REGISTER_RESET = 'PHONE_CLEAN_REGISTER_RESET'

export const PHONE_CLEAN_DELETE_REQUEST = 'PHONE_CLEAN_DELETE_REQUEST'
export const PHONE_CLEAN_DELETE_SUCCESS = 'PHONE_CLEAN_DELETE_SUCCESS'
export const PHONE_CLEAN_DELETE_FAIL = 'PHONE_CLEAN_DELETE_FAIL'
export const PHONE_CLEAN_DELETE_RESET = 'PHONE_CLEAN_DELETE_RESET'

export const PHONE_CLEAN_UPDATE_REQUEST = 'PHONE_CLEAN_UPDATE_REQUEST'
export const PHONE_CLEAN_UPDATE_SUCCESS = 'PHONE_CLEAN_UPDATE_SUCCESS'
export const PHONE_CLEAN_UPDATE_FAIL = 'PHONE_CLEAN_UPDATE_FAIL'
export const PHONE_CLEAN_UPDATE_RESET = 'PHONE_CLEAN_UPDATE_RESET'

export const PHONE_IMPORT_REQUEST = 'PHONE_IMPORT_REQUEST'
export const PHONE_IMPORT_SUCCESS = 'PHONE_IMPORT_SUCCESS'
export const PHONE_IMPORT_FAIL = 'PHONE_IMPORT_FAIL'
export const PHONE_IMPORT_RESET = 'PHONE_IMPORT_RESET'