export const PHONE_LIST_REQUEST = 'PHONE_LIST_REQUEST'
export const PHONE_LIST_SUCCESS = 'PHONE_LIST_SUCCESS'
export const PHONE_LIST_FAIL = 'PHONE_LIST_FAIL'
export const PHONE_LIST_RESET = 'PHONE_LIST_RESET'

export const PHONE_REGISTER_REQUEST = 'PHONE_REGISTER_REQUEST'
export const PHONE_REGISTER_SUCCESS = 'PHONE_REGISTER_SUCCESS'
export const PHONE_REGISTER_FAIL = 'PHONE_REGISTER_FAIL'
export const PHONE_REGISTER_RESET = 'PHONE_REGISTER_RESET'

export const PHONE_DELETE_REQUEST = 'PHONE_DELETE_REQUEST'
export const PHONE_DELETE_SUCCESS = 'PHONE_DELETE_SUCCESS'
export const PHONE_DELETE_FAIL = 'PHONE_DELETE_FAIL'
export const PHONE_DELETE_RESET = 'PHONE_DELETE_RESET'

export const PHONE_UPDATE_REQUEST = 'PHONE_UPDATE_REQUEST'
export const PHONE_UPDATE_SUCCESS = 'PHONE_UPDATE_SUCCESS'
export const PHONE_UPDATE_FAIL = 'PHONE_UPDATE_FAIL'
export const PHONE_UPDATE_RESET = 'PHONE_UPDATE_RESET'