export const PHONE_TEMP_LIST_REQUEST = 'PHONE_TEMP_LIST_REQUEST'
export const PHONE_TEMP_LIST_SUCCESS = 'PHONE_TEMP_LIST_SUCCESS'
export const PHONE_TEMP_LIST_FAIL = 'PHONE_TEMP_LIST_FAIL'
export const PHONE_TEMP_LIST_RESET = 'PHONE_TEMP_LIST_RESET'

export const PHONE_TEMP_COUNT_REQUEST = 'PHONE_TEMP_COUNT_REQUEST'
export const PHONE_TEMP_COUNT_SUCCESS = 'PHONE_TEMP_COUNT_SUCCESS'
export const PHONE_TEMP_COUNT_FAIL = 'PHONE_TEMP_COUNT_FAIL'
export const PHONE_TEMP_COUNT_RESET = 'PHONE_TEMP_COUNT_RESET'