export const UPLOAD_CSV_REQUEST = 'UPLOAD_CSV_REQUEST'
export const UPLOAD_CSV_SUCCESS = 'UPLOAD_CSV_SUCCESS'
export const UPLOAD_CSV_FAIL = 'UPLOAD_CSV_FAIL'
export const UPLOAD_CSV_RESET = 'UPLOAD_CSV_RESET'
